version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  api:
    build: ./server
    container_name: api
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/appdb}
    expose:
      - "5000"
    networks:
      - appnet

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:

volumes:
  mongo_data:
